# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sektoraler Heilpraktiker für Physiotherapie - Fortbildung und Prüfung
email: info@heilpraktiker-physiotherapie.com    
description: Heilpraktiker für Physiotherapie - Fortbildung inklusive Prüfung zur Anerkennung nach Aktenlage, in NRW, Niedersachsen, Rheinland-Pfalz, Hessen, Baden-Württemberg, Bayern, Sachsen, Thüringen, Berlin und anderen Bundesländern  
logo: "/assets/images/logosvg.svg"
logopng: "/assets/images/hpptlogo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hpphysio.com" # the base hostname & protocol for your site
repository: heilpraktiker-physiotherapie/heilpraktiker-physiotherapie.github.io

paginate:	2 # The number of posts to show per page on your homepage
paginate_path: '/blog/page:num/'

name: 'Arne Brödel'
bio: Physiotherapeut, Heilpraktiker für Physiotherapie
author_image: "/assets/images/author.jpg"
twitter_username: PhysioHP
twitter_url: https://twitter.com/PhysioHP
facebook_url: https://www.facebook.com/HeilpraktikerPhysiotherapie/
googleplus_url: https://plus.google.com/+Heilpraktikerphysiotherapiecom
youtube_url: https://www.youtube.com/c/Heilpraktikerphysiotherapiecom

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  
#permalink: /blog/:title


gems:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-sitemap
  
